import { useEffect, useState } from "react";
import { MOCK_SESSIONS, MOCK_SESSION_LABELS } from "../mock/sessions";
import type { SessionDecisionResponse } from "../types/contract";

/**
 * Live pipeline demo view.
 *
 * Without `VITE_API_BASE_URL` configured (the case for the hosted static
 * build), reads from the mock fixture module exactly as before. When that
 * env var is set, POSTs the real, pre-signed request bodies in
 * `public/live_demo_requests.json` (generated by `run_live_demo_export.py`
 * from `service/demo_scenarios.py`) to a running service's
 * `/sessions/decide` and renders the genuine response -- the three
 * scenarios that depend on causal history (legitimate-allowed, rapid
 * reuse, behavioral-only) work because that same service seeds their
 * warm-up sessions at startup (`service/demo_seed.py`), so the request
 * bodies here reflect real accumulated history, not a first-ever call.
 */

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL as string | undefined;

type LiveState =
  | { status: "disabled" }
  | { status: "loading" }
  | { status: "ready"; sessions: Record<string, SessionDecisionResponse> }
  | { status: "error"; message: string };

function useLiveDemoSessions(): LiveState {
  const [state, setState] = useState<LiveState>(API_BASE_URL ? { status: "loading" } : { status: "disabled" });

  useEffect(() => {
    if (!API_BASE_URL) return;
    // The demo scenarios' warm-up history is real, accumulated server-side
    // state (see service/demo_seed.py) -- POSTing the same "final" session
    // twice genuinely mutates it twice, unlike an idempotent GET. An
    // AbortController cancels the in-flight requests on cleanup (a real
    // navigate-away, or React StrictMode's dev-only mount/cleanup/remount
    // cycle) rather than just ignoring their results. On a fast local
    // server, StrictMode's first (aborted) attempt may still land before
    // the cancellation propagates, so a second, real request can still
    // reach the server in development; that surviving second request is
    // the one whose result actually renders, and it reflects genuine
    // accumulated state either way. This does not happen in a production
    // build, which never double-invokes effects.
    const controller = new AbortController();

    async function run() {
      try {
        const requestsRes = await fetch("/live_demo_requests.json", { signal: controller.signal });
        if (!requestsRes.ok) throw new Error(`failed to load live_demo_requests.json (${requestsRes.status})`);
        const requests = (await requestsRes.json()) as Record<string, unknown>;

        const entries = await Promise.all(
          Object.entries(requests).map(async ([sessionId, body]) => {
            const res = await fetch(`${API_BASE_URL}/sessions/decide`, {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify(body),
              signal: controller.signal,
            });
            if (!res.ok) throw new Error(`/sessions/decide returned ${res.status} for ${sessionId}`);
            return [sessionId, (await res.json()) as SessionDecisionResponse] as const;
          }),
        );

        setState({ status: "ready", sessions: Object.fromEntries(entries) });
      } catch (error) {
        if (error instanceof DOMException && error.name === "AbortError") return;
        setState({ status: "error", message: error instanceof Error ? error.message : String(error) });
      }
    }

    void run();
    return () => {
      controller.abort();
    };
  }, []);

  return state;
}

function stageClass(status: "fired" | "passed" | "pending"): string {
  return `pipeline-stage pipeline-stage--${status}`;
}

function PipelineView({ session }: { session: SessionDecisionResponse }) {
  const layer1Fired = session.baseline.verification_reasons.length > 0;
  const layer2Fired = session.baseline.scope_reasons.length > 0;
  const rulesBlocked = session.baseline.blocked;
  const layer3Reached = !rulesBlocked;
  const layer3Fired = session.ensemble.source === "behavioral";

  return (
    <div className="pipeline-stages">
      <div className={stageClass(layer1Fired ? "fired" : "passed")}>
        <div className="pipeline-stage__label">Layer 1 — Mandate verification</div>
        {layer1Fired ? (
          <span className="badge badge--block">
            {session.baseline.verification_reasons.join(", ")}
          </span>
        ) : (
          <span className="badge badge--allow">passed</span>
        )}
      </div>

      <div
        className={stageClass(
          !layer3Reached && !layer1Fired ? "fired" : layer2Fired ? "fired" : layer1Fired ? "pending" : "passed",
        )}
      >
        <div className="pipeline-stage__label">Layer 2 — Scope enforcement</div>
        {layer1Fired ? (
          <span className="badge badge--warn">not reached</span>
        ) : layer2Fired ? (
          <span className="badge badge--block">{session.baseline.scope_reasons.join(", ")}</span>
        ) : (
          <span className="badge badge--allow">passed</span>
        )}
      </div>

      <div className={stageClass(!layer3Reached ? "pending" : layer3Fired ? "fired" : "passed")}>
        <div className="pipeline-stage__label">Layer 3 — Behavioral model</div>
        {!layer3Reached ? (
          <span className="badge badge--warn">not reached</span>
        ) : (
          <span className={`badge ${layer3Fired ? "badge--block" : "badge--allow"}`}>
            score {session.ensemble.behavioral_score?.toFixed(3) ?? "n/a"}
          </span>
        )}
      </div>

      <div className={stageClass("passed")}>
        <div className="pipeline-stage__label">Layer 4 — Reasoning &amp; audit</div>
        <span className="badge badge--allow">narrated</span>
      </div>
    </div>
  );
}

function NarrativeView({ session }: { session: SessionDecisionResponse }) {
  if (!session.narrative) {
    return <p className="section-note">This session has not been narrated.</p>;
  }
  const n = session.narrative;
  const isBlocked = n.verdict_summary !== "allowed";
  return (
    <div>
      <div className="narrative-verdict">
        <span className={`badge ${isBlocked ? "badge--block" : "badge--allow"}`}>{n.verdict_summary}</span>
        <span className="narrative-meta">
          {n.model} · {new Date(n.generated_at).toLocaleString()}
        </span>
      </div>
      <p className="narrative-text">{n.narrative}</p>
      {(n.rule_citations.length > 0 || n.feature_citations.length > 0) && (
        <div className="citation-lists">
          {n.rule_citations.length > 0 && (
            <div className="citation-group">
              <span className="citation-group__label">Rules cited</span>
              {n.rule_citations.map((rule) => (
                <span className="badge badge--block" key={rule}>
                  {rule}
                </span>
              ))}
            </div>
          )}
          {n.feature_citations.length > 0 && (
            <div className="citation-group">
              <span className="citation-group__label">Features cited</span>
              {n.feature_citations.map((feature) => (
                <span className="badge badge--warn" key={feature}>
                  {feature}
                </span>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function AttributionView({ session }: { session: SessionDecisionResponse }) {
  if (!session.attribution) {
    return (
      <p className="section-note">
        No attribution to show — the rules layers already decided this session, so Layer 3 was
        never scored.
      </p>
    );
  }
  const maxAbs = Math.max(...session.attribution.map((row) => Math.abs(row.shap_value)));
  return (
    <div>
      {session.attribution.map((row) => (
        <div className="attribution-row" key={row.feature}>
          <span style={{ width: 220, flexShrink: 0, color: "var(--slate)" }}>{row.feature}</span>
          <span className="attribution-bar-track">
            <span
              className={`attribution-bar ${row.shap_value >= 0 ? "attribution-bar--positive" : "attribution-bar--negative"}`}
              style={{ width: `${(Math.abs(row.shap_value) / maxAbs) * 100}%` }}
            />
          </span>
          <span style={{ width: 60, textAlign: "right" }}>{row.shap_value.toFixed(3)}</span>
        </div>
      ))}
    </div>
  );
}

export default function LiveDemo() {
  const [selectedId, setSelectedId] = useState(MOCK_SESSIONS[0].session_id);
  const live = useLiveDemoSessions();

  const liveSession = live.status === "ready" ? live.sessions[selectedId] : undefined;
  const session = liveSession ?? MOCK_SESSIONS.find((s) => s.session_id === selectedId)!;

  const sourceNote =
    live.status === "ready"
      ? "Real responses from a live /sessions/decide call against a running instance of the API service -- not fixtures."
      : live.status === "loading"
        ? "Connecting to the configured API service..."
        : live.status === "error"
          ? `Could not reach the live API service (${live.message}); showing static fixtures instead.`
          : "Fixtures matching the real API service's response contract, generated by walking the same " +
            "detection pipeline the evaluation harness runs against real generated traffic. Not yet " +
            "wired to a live call against the running service.";

  return (
    <>
      <div className="panel">
        <div className="page-intro">
          <span className="page-intro__eyebrow">New here?</span>
          <p>
            Each button below is a full synthetic transaction — a signed authorization ("mandate")
            plus a purchase attempt. Click one to watch all four checks run against it in order and
            see the real verdict: which check fired (if any), what evidence it points to, and a
            plain-language explanation of why.
          </p>
        </div>
        <h2 className="section-title">Pick a session</h2>
        <p className="section-note">{sourceNote}</p>
        <div className="session-picker">
          {MOCK_SESSIONS.map((s) => (
            <button
              key={s.session_id}
              className={s.session_id === selectedId ? "active" : ""}
              onClick={() => setSelectedId(s.session_id)}
            >
              {MOCK_SESSION_LABELS[s.session_id]}
            </button>
          ))}
        </div>
      </div>

      <div className="panel">
        <h2 className="section-title">Decision pipeline</h2>
        <PipelineView session={session} />
      </div>

      <div className="panel">
        <h2 className="section-title">Feature attribution</h2>
        <p className="section-note">
          Signed SHAP contribution per feature — positive pushes the score toward "attack",
          negative toward "legitimate".
        </p>
        <AttributionView session={session} />
      </div>

      <div className="panel">
        <h2 className="section-title">Decision narrative</h2>
        <p className="section-note">
          Plain-language explanation of the verdict above, citing exactly which check fired and
          why — narration only, produced after the verdict and structurally unable to change it.
        </p>
        <NarrativeView session={session} />
      </div>
    </>
  );
}
